### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by kokoko3k** [cseelus/monego#1]
Thank you so much for this, i've been struggling to find something that works, and i finally found it.
Is there any reason why bold italic is missing?
I've just made it in fontforge and seems to work well.

**Comment by cseelus** [comment]
A separate bold italic verison? Very nice! 

You can open a PR to add it or send it to me and I'll add it if you like.

**Comment by kokoko3k** [comment]
Here it is:
https://github.com/kokoko3k/ModFonts/blob/master/Monego/Monego-BoldItalic.otf

**Comment by cseelus** [comment]
Thanks, I included it in this repo

**Comment by astrolemonade** [comment]
This is great! Thank you!
