### ISSUE TITLE
Clarify license/copyright

### ISSUE THREAD

**Issue by dabrahams** [cseelus/monego#12]
This is wonderful, but I'd like to make sure I'm not violating any copyrights by using it.  Could you say something about that in the README?

**Comment by cseelus** [comment]
Thx.

It’s a fork of a fork of a recreated version of Monaco. Depending on where you live, you might want to avoid it.

**Comment by dabrahams** [comment]
I guess maybe it depends what "recreated" means.  I live in the US, and if the original "recreation" was done by reproducing appearance rather than copying numbers, it [seems like it should be fine](https://signbrad.com/2018/11/03/how-can-two-typestyles-appear-identical-without-constituting-copyright-infringement/) for me to use it.

**Comment by cseelus** [comment]
All glyphs were altered and in case of the bold variant widened via Fontforge.

They were not recreated/improved one by one manually, which is what I strife to (let) do with this font some day.
