### ISSUE TITLE
Wierd ligatures from character #

### ISSUE THREAD

**Issue by gmtborges** [cseelus/monego#16]
The default ligatures of the # char are weird with this font. So I removed them. Here is a screenshot with those strange ligatures.
![Screenshot from 2024-01-04 09-27-38](https://github.com/cseelus/monego/assets/4812010/b0ecea24-a560-4e54-9f24-fa3cfe7a9d48)

And if you remove
![image](https://github.com/cseelus/monego/assets/4812010/acd83499-1df7-478e-9a0a-775dc28fdeab)

**Comment by cseelus** [comment]
Neat, can you open a PR?

**Comment by gmtborges** [comment]
Of course, I'll open it.
