### ISSUE TITLE
A version with font ligatures?

### ISSUE THREAD

**Issue by rodrigocfd** [cseelus/monego#2]
How about a version with font ligatures? Maybe a _Liga Monego_, following the convetion of [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer), which may be a starting point.

**Comment by cseelus** [comment]
@rodrigocfd Is there a reason why this should be released as a separate version instead of just updating the existing font files with ligatures?

**Comment by rodrigocfd** [comment]
@cseelus Some people don't like ligatures. An unique version with ligatures would put these people off. Plus, I remember one situation when I didn't want to see the ligatures, when I was debugging some code that had syntax errors. Other than that, I would like to see ligatures all the time.

I like the approach taken by Ligaturizer: they just made another version of the font with the name prefixed with "Liga". Here, we would then have "Liga Monego".

**Comment by cseelus** [comment]
Ligatures need be be explicitly enabled in any editor/terminal I used so far, so people who dislike them could just not use them:

<img width="416" alt="Screen Shot 2019-10-03 at 17 31 49" src="https://user-images.githubusercontent.com/3188392/66141293-bce62300-e603-11e9-9afb-d76616671f45.png">

However I ran into an [issue with the kerning of the ligaturized font](https://github.com/ToxicFrog/Ligaturizer/issues/74), so I added it as a separate font, as you suggested (and per the Ligaturizer 2.0 default settings). If I can resolve that issue, I will update "Liga Monego".
