### ISSUE TITLE
Some chars in BoldItalic have strange spacing

### ISSUE THREAD

**Issue by AlynxZhou** [cseelus/monego#5]
![Screenshot from 2022-03-07 18-21-18](https://user-images.githubusercontent.com/8444615/157013108-8c0c6e86-81c0-474c-bf2d-1747ce61564a.png)

In this screenshot, the `r` in `warn` is BoldItalic, and it has a wrong left spacing, however, the italic `r` in `logger` is OK, I am not sure if there are still other wrong chars, but the BoldItalic one always looks strange (compared with Italic version).

**Comment by cseelus** [comment]
Which version of the font are you using, normal, ligatures or Nerd Font?

**Comment by AlynxZhou** [comment]
> Which version of the font are you using, normal, ligatures or Nerd Font?

Normal version.

**Comment by cseelus** [comment]
Can you try this version: https://github.com/cseelus/monego/pull/4/commits/502eb55769b57d3472966b8c64bd5cdfc6bd57f0

**Comment by AlynxZhou** [comment]
Sorry for the late reply.

![Screenshot from 2022-03-10 08-43-45](https://user-images.githubusercontent.com/8444615/157564446-6cd07578-274e-4a88-acc2-81afb7a32137.png)

592eb55 looks better, could you fix this for normal version? Because I don't want to use nerd version. Thanks

**Comment by cseelus** [comment]
Hi @AlynxZhou 

Please check out this (normal) version:

[Monego.zip](https://github.com/cseelus/monego/files/8385594/Monego.zip)

**Comment by AlynxZhou** [comment]
> Hi @AlynxZhou
> 
> Please check out this (normal) version:
> 
> [Monego.zip](https://github.com/cseelus/monego/files/8385594/Monego.zip)

Sorry for the late reply, this one's bold-italic works fine, but it seems to break normal italic chars, please see the `config`'s `f`, `i` in comment:

New:

![Screenshot from 2022-04-18 10-57-46](https://user-images.githubusercontent.com/8444615/163747762-09644683-fdc2-4695-8406-1d3c0e330a64.png)

Old:

![Screenshot from 2022-04-18 10-59-03](https://user-images.githubusercontent.com/8444615/163747922-1d0d8325-50cd-4faf-a9d4-cc5192f58e8c.png)

**Comment by cseelus** [comment]
Strange, will have to look for a different method with better letter-spacing. Thx for your feedback.

**Comment by mostafaqanbaryan** [comment]
![image](https://user-images.githubusercontent.com/94293456/168046089-438cf654-062c-4ea8-8bf9-4155fd6e0c7d.png)

I wanted to add that this problem exists in terminal/vim and it's really bothering me.
`Monego` and `Monego-Nerd` have no problem and `'` is center. But `Monego-with-ligatures`, which is a great font by the way, this problem occurs and makes me think there is space character before `'`.

**Comment by AlynxZhou** [comment]
> Strange, will have to look for a different method with better letter-spacing. Thx for your feedback.

Hi, any update on this?

**Comment by cseelus** [comment]
Not yet. We've been trying to batch fix those spacing issues, but at the moment it looks like the only way to fix it would be to manually adjust each char, which is beyond the scope of this little fork here.

**Comment by AlynxZhou** [comment]
Could you share how you make bold/italic fonts from the regular one? (maybe scripts or other operations) I really love this custom version, but I am afraid that re-distributing such a copy right font is not OK, but distributing tweak scripts and let user gather font and patch by themselves is always ok.

**Comment by cseelus** [comment]
@AlynxZhou Check out this PR: https://github.com/cseelus/monego/pull/4
