### ISSUE TITLE
Feature Request: submit to Homebrew

### ISSUE THREAD

**Issue by tshu-w** [cseelus/monego#7]
Hi, I find you are using macOS and Homebrew either. It would be much appreciated if you could make this available on `homebrew/cask-fonts`

**Comment by cseelus** [comment]
Since I can’t submit this Font to Google Fonts, I don’t think there is a way they would accept its inclusion: https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md
